version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "12:00"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "12:00"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "12:00"
