version: "3.9"

services:
  bot:
    image: "ghcr.io/dawnbrandbots/bastion-bot:${DOCKER_TAG:-latest}"
    environment:
      DEBUG: "*"
      DISCORD_TOKEN:
      SEARCH_API:
      IMAGE_HOST:
      DISCORD_SHARD: "{{.Task.Slot}}"
      DISCORD_TOTAL_SHARDS:
      BOT_LOGGER_WEBHOOK: "${BOT_LOGGER_WEBHOOK:-}"
      BOT_PRESENCE: "${BOT_PRESENCE:-}"
      BOT_MOTD: "${BOT_MOTD:-}"
    deploy:
      replicas: ${DISCORD_TOTAL_SHARDS}
    restart: unless-stopped
    logging:
      driver: journald
networks:
  default:
    external: true
    name: royal-magical-library_default
