version: "3.9"

services:
  bot:
    image: "ghcr.io/dawnbrandbots/bastion-bot:${DOCKER_TAG:-latest}"
    environment:
      DEBUG: "*"
      DISCORD_TOKEN:
      API_URL:
      HEALTHCHECK_BOT_SNOWFLAKE:
      DISCORD_SHARD: "{{.Task.Slot}}"
      DISCORD_TOTAL_SHARDS:
      BOT_LOGGER_WEBHOOK: "${BOT_LOGGER_WEBHOOK:-}"
      BOT_PRESENCE: "${BOT_PRESENCE:-}"
      BOT_MOTD: "${BOT_MOTD:-}"
      BOT_NO_DIRECT_MESSAGE_SEARCH: 1
    logging:
      driver: journald
    deploy:
      replicas: ${DISCORD_TOTAL_SHARDS}
      update_config:
        order: start-first
      placement:
        constraints:
          - node.role==manager
